Assets/Scripts/Templates/TTuple.cs
- Tuples now use explicitly private members.
- Tuples also check for null in Equals(...)
=> Cleaned up Tuple helper class

Assets/Scenes/Experiments/FallingCoil/FallingCoil.pc.unity, Assets/Scenes/Experiments/FaradaysLaw/FaradaysLaw.pc.unity, Assets/Scenes/Experiments/Pendulum/Pendulum.pc.unity
=> Maroon-74 Experiments cannot reset

unity/Assets/0Refactored/reusablePrefabs/questManager/MainQuest.prefab, unity/Assets/0Refactored/reusablePrefabs/questManager/SubQuest.prefab
=> Maroon-134 [Quest manager] Quest manager blocks teleporting

Assets/Scenes/Experiments/FallingCoil/FallingCoil.vr.unity, Packages/manifest.json, ProjectSettings/ProjectVersion.txt, README.md
=> Maroon-198 Fix Font Size in Falling Coil

unity/Packages/manifest.json
=> Maroon-201 Utilities LanguageManager Update

unity/Assets/0Refactored/reusableScripts/scrSceneAssetSerializer.cs, unity/Assets/0Refactored/reusableScripts/scrSceneAssetSerializer.cs.meta, unity/Assets/0Refactored/scenes/experiments/CoulombsLaw/prefabs/ExperimentPreviewCoulomb.prefab, unity/Assets/0Refactored/scenes/experiments/FallingCoil/prefabs/ExperimentPreviewFallingCoil.prefab, unity/Assets/0Refactored/scenes/experiments/FaradaysLaw/prefabs/ExperimentPreviewFaradaysLaw.prefab, unity/Assets/0Refactored/scenes/experiments/HuygensPrinciple/prefabs/ExperimentPreviewHuygensPrinciple.prefab, unity/Assets/0Refactored/scenes/experiments/Pendulum/prefabs/ExperimentPreviewPendulum.prefab, unity/Assets/0Refactored/scenes/experiments/TriboelectricExperiment/prefabs/ExperimentPreviewTriboelectric.prefab, unity/Assets/0Refactored/scenes/experiments/VanDeGraaffBalloon/prefabs/ExperimentPreviewVanDeGraffBalloon.prefab, unity/Assets/0Refactored/scenes/experiments/VanDeGraaffGenerator/prefabs/ExperimentPreviewVanDeGraaffGenerator.prefab, unity/Assets/0Refactored/scenes/experiments/Whiteboard/prefabs/ExperimentPreviewWhiteboard.prefab, unity/Assets/0Refactored/scenes/laboratory/prefabs/InfoSign/Scripts/scrInfoSignEnterScene.cs, unity/Assets/0Unused/unusedModels/_glassrod/Materials.meta, unity/Assets/0Unused/unusedModels/_glassrod/Materials/Glass.mat, unity/Assets/0Unused/unusedModels/_glassrod/Materials/Glass.mat.meta
=> Fix scene references in build

unity/Assets/0Refactored/reusableScripts/PlatformControls/PC/PC_LocalizedDropDown.cs, unity/Assets/0Refactored/scenes/experiments/CoulombsLaw/Scripts/PC_Dropdown.cs, unity/Assets/0Refactored/scenes/experiments/CoulombsLaw/Scripts/PC_Tooltip.cs
=> Maroon-217 [PC] Dropdowns and Tooltips do not update language

unity/Assets/0Refactored/scenes/laboratory/prefabs/InfoSign/InfoSign.prefab
=> can enter scene via button click (pc)

unity/Assets/0Refactored/reusableGui/Menu/PrefabsBase/preMenu.prefab, unity/Assets/0Refactored/reusableGui/Menu/PrefabsColumns/scrMenuColumnPauseMenu.cs
=> Disable pause menu by default and restore time scale correctly

unity/Assets/0Refactored/scenes/experiments/CoulombsLaw/CoulombsLaw.pc.unity, unity/Assets/0Refactored/scenes/experiments/FallingCoil/FallingCoil.pc.unity, unity/Assets/0Refactored/scenes/experiments/FaradaysLaw/FaradaysLaw.pc.unity, unity/Assets/0Refactored/scenes/experiments/HuygensPrinciple/HuygensPrinciple.pc.unity, unity/Assets/0Refactored/scenes/experiments/Pendulum/Pendulum.pc.unity, unity/Assets/0Refactored/scenes/experiments/VanDeGraaffBalloon/VandeGraaffExperiment2.pc.unity, unity/Assets/0Refactored/scenes/experiments/VanDeGraaffGenerator/VandeGraaffExperiment1.pc.unity, unity/Assets/0Refactored/scenes/experiments/Whiteboard/Whiteboard.pc.unity
=> Maroon-224 [PC] Fix Blurred Experiments

unity/Assets/0Refactored/Editor/BuildPlayer.cs
=> Maroon-237 Default Screen Size

unity/Assets/0Refactored/scenes/experiments/HuygensPrinciple/scripts/SlitPlate.cs
Close #260 This one-liner does the trick.
=> Maroon-260_FixSlitPlateWaveGenerator

unity/Assets/0Refactored/Editor/BuildPlayer.cs
=> Maroon-258 Fix Platform Switch in Build Script

unity/Assets/0Refactored/reusablePrefabs/experimentRoom/Prefabs/ExperimentRoom.prefab, unity/Assets/0Refactored/reusablePrefabs/experimentRoom/Scripts.meta, unity/Assets/0Refactored/reusablePrefabs/experimentRoom/Scripts/ExperimentRoomLightning.cs, unity/Assets/0Refactored/reusablePrefabs/experimentRoom/Scripts/ExperimentRoomLightning.cs.meta
=> Maroon-270 Disable Roof and Front Wall of the Experiment Room during Light Baking

unity/Assets/0Refactored/scenes/experiments/PointWave/scripts/PointWave_SelectionHandler.cs
=> Fixed using directive

unity/Assets/0Refactored/Editor/BuildPlayer.cs
=> Maroon-275 Experiment Export For Plattform

unity/Assets/0Refactored/reusablePrefabs/questManager.meta, unity/Packages/manifest.json, unity/Packages/packages-lock.json, unity/ProjectSettings/PackageManagerSettings.asset
=> Remove quicksearch

unity/Assets/Maroon/reusableGui/NewUI/Resources/ValueDisplay.prefab, unity/Assets/Maroon/reusableGui/NewUI/Resources/ValueDisplay.prefab.meta, unity/Assets/Maroon/reusableGui/NewUI/Scripts/Runtime/QuantityValueDisplay.cs, unity/Assets/Maroon/reusableGui/NewUI/Scripts/Runtime/QuantityValueDisplay.cs.meta, unity/Assets/Maroon/reusableScripts/Physics/Electromagnetism/Charge.cs, unity/Assets/Maroon/reusableScripts/PlatformControls/BaseControls/GrounderMovement.cs, unity/Assets/Maroon/reusableScripts/PlatformControls/PC/PC_GrounderMovement.cs, unity/Assets/Maroon/scenes/experiments/VanDeGraaffGenerator/Scripts/VanDeGraaff/BalloonController.cs, unity/Assets/Maroon/scenes/experiments/VanDeGraaffGenerator/Scripts/VanDeGraaff/VanDeGraaffController.cs, unity/Assets/Maroon/scenes/experiments/VanDeGraaffGenerator/Scripts/VanDeGraaffNetworkSync.cs, unity/Assets/Maroon/scenes/experiments/VanDeGraaffGenerator/VandeGraaffBalloon.pc.unity, unity/Assets/Maroon/scenes/experiments/VanDeGraaffGenerator/VandeGraaffGenerator.pc.unity
=> Maroon-232 New UI Layouts - VanDeGraaffGenerator

unity/Assets/Maroon/reusableGui/NewUI/Scripts/Runtime/QuantityPropertyView.cs
=> Maroon-326 [QuantityPropertyView] Language Support

unity/Assets/Maroon/reusableGui/NewUI/Scripts/Runtime/QuantityPropertyView.cs
=> Maroon-327 [QuantityPropertyView] OnQuantityViewVisible Event
